Repository FuelLabs/sway-libs, pull requests merged in 2024-10, with the labels that each got.

#305 Update to forc v0.66.2, fuel-core v0.40. and fuels-rs v0.66.9
  .github/workflows/ci.yml
  .github/workflows/gh-pages.yml
  CHANGELOG.md
  README.md
  examples/Forc.lock
  libs/Forc.lock
  tests/Cargo.toml
  tests/Forc.lock
  tests/src/bytecode/tests/utils/mod.rs
Labels: Improvement, Repo Misc

#302 chore: fix md typos
  CHANGELOG.md
  docs/book/src/asset/base.md
  docs/book/src/asset/metadata.md
  docs/book/src/asset/supply.md
  docs/book/src/bytecode/index.md
  docs/book/src/index.md
  docs/book/src/pausable/index.md
  docs/book/src/signed_integers/index.md
Labels: Documentation

#306 Update SRC-7 naming
  CHANGELOG.md
  docs/book/spell-check-custom-words.txt
  docs/book/src/asset/index.md
  docs/book/src/asset/metadata.md
Labels: Documentation, Lib: Asset
