Repository FuelLabs/sway-libs, pull requests merged in 2024-12, with the labels that each got.

#310 Reentrancy Tests with Proxy
  CHANGELOG.md
  tests/Forc.lock
  tests/Forc.toml
  tests/src/reentrancy/mod.rs
  tests/src/reentrancy/reentrancy_attacker_abi/src/main.sw
  tests/src/reentrancy/reentrancy_attacker_contract/src/main.sw
  tests/src/reentrancy/reentrancy_proxy_abi/Forc.lock
  tests/src/reentrancy/reentrancy_proxy_abi/Forc.toml
  tests/src/reentrancy/reentrancy_proxy_abi/src/main.sw
  tests/src/reentrancy/reentrancy_proxy_contract/Forc.lock
  tests/src/reentrancy/reentrancy_proxy_contract/Forc.toml
  tests/src/reentrancy/reentrancy_proxy_contract/src/main.sw
  tests/src/reentrancy/reentrancy_target_abi/src/main.sw
  tests/src/reentrancy/reentrancy_target_contract/src/main.sw
Labels: New Feature, Lib: Security

#311 Fix readme link
  README.md
Labels: Bug, Documentation

#314 Prepare master for version v0.24.1
  CHANGELOG.md
  Cargo.toml
  README.md
  docs/book/src/getting_started/index.md
Labels: Release
