Repository FuelLabs/sway-libs, pull requests merged in 2024-02, with the labels that each got.

#212 Bump Libraries to forc v0.50 and rust v0.75.0
  .github/workflows/ci.yml
  libs/fixed_point/src/ifp128.sw
  libs/fixed_point/src/ifp256.sw
  libs/fixed_point/src/ifp64.sw
  libs/fixed_point/src/ufp128.sw
  libs/fixed_point/src/ufp32.sw
  libs/fixed_point/src/ufp64.sw
  libs/ownership/src/events.sw
  libs/signed_integers/src/i128.sw
  libs/signed_integers/src/i16.sw
  libs/signed_integers/src/i256.sw
  libs/signed_integers/src/i32.sw
  libs/signed_integers/src/i64.sw
  libs/signed_integers/src/i8.sw
  tests/src/native_asset/Forc.toml
Labels: Improvement, Repo Misc

#211 Bytecode Root Solver Library
  README.md
  libs/Forc.toml
  libs/bytecode/.docs/bytecode-logo-dark-theme.png
  libs/bytecode/.docs/bytecode-logo-light-theme.png
  libs/bytecode/Forc.toml
  libs/bytecode/README.md
  libs/bytecode/SPECIFICATION.md
  libs/bytecode/src/lib.sw
  libs/bytecode/src/utils.sw
  tests/Cargo.toml
  tests/Forc.toml
  tests/src/bytecode/.gitignore
  tests/src/bytecode/mod.rs
  tests/src/bytecode/test_artifacts/complex_contract/Forc.toml
  tests/src/bytecode/test_artifacts/complex_contract/src/main.sw
  tests/src/bytecode/test_artifacts/simple_contract/Forc.toml
  tests/src/bytecode/test_artifacts/simple_contract/src/main.sw
  tests/src/bytecode/test_artifacts/simple_predicate/Forc.toml
  tests/src/bytecode/test_artifacts/simple_predicate/src/main.sw
  tests/src/bytecode/test_contract/Forc.toml
  tests/src/bytecode/test_contract/src/main.sw
  tests/src/bytecode/tests/functions/compute_bytecode_root.rs
  tests/src/bytecode/tests/functions/compute_bytecode_root_with_configurables.rs
  tests/src/bytecode/tests/functions/compute_predicate_address.rs
  tests/src/bytecode/tests/functions/compute_predicate_address_with_configurables.rs
  tests/src/bytecode/tests/functions/mod.rs
  tests/src/bytecode/tests/functions/predicate_address_from_root.rs
  tests/src/bytecode/tests/functions/swap_configurables.rs
  tests/src/bytecode/tests/functions/verify_contract_bytecode.rs
  tests/src/bytecode/tests/functions/verify_contract_bytecode_with_configurables.rs
  tests/src/bytecode/tests/functions/verify_predicate_address.rs
  tests/src/bytecode/tests/functions/verify_predicate_address_with_configurables.rs
  tests/src/bytecode/tests/mod.rs
  tests/src/bytecode/tests/utils/mod.rs
  tests/src/harness.rs
Labels: New Feature, Bytecode Solver

#213 Fix incorrect native asset URL in README
  README.md
Labels: Documentation
