Repository FuelLabs/sway-libs, pull requests merged in 2024-05, with the labels that each got.

#242 Hotfix: Fix CI to forc v0.56.0 and tests to fuels v0.57.0
  .github/workflows/ci.yml
  .github/workflows/gh-pages.yml
  examples/Cargo.toml
  tests/Cargo.toml
  tests/src/bytecode/tests/utils/mod.rs
  tests/src/native_asset/tests/functions/burn.rs
  tests/src/native_asset/tests/functions/decimals.rs
  tests/src/native_asset/tests/functions/metadata.rs
  tests/src/native_asset/tests/functions/name.rs
  tests/src/native_asset/tests/functions/set_decimals.rs
  tests/src/native_asset/tests/functions/set_metadata.rs
  tests/src/native_asset/tests/functions/set_name.rs
  tests/src/native_asset/tests/functions/set_symbol.rs
  tests/src/native_asset/tests/functions/symbol.rs
  tests/src/native_asset/tests/functions/total_supply.rs
  tests/src/native_asset/tests/utils/setup.rs
  tests/src/reentrancy/reentrancy_attacker_abi/src/main.sw
  tests/src/reentrancy/reentrancy_attacker_contract/src/main.sw
  tests/src/reentrancy/reentrancy_target_contract/src/main.sw
Labels: Improvement, Repo Misc

#243 Bump Merkle Library to use fuel-merkle v0.49
  examples/Cargo.toml
  examples/merkle/mod.rs
  tests/Cargo.toml
  tests/src/merkle_proof/tests/utils/mod.rs
Labels: Improvement, Lib: Cryptography

#240 Fix unused lines from fixed point library
  libs/src/fixed_point/ifp128.sw
  libs/src/fixed_point/ifp256.sw
  libs/src/fixed_point/ifp64.sw
  libs/src/fixed_point/ufp128.sw
  libs/src/fixed_point/ufp32.sw
Labels: Improvement

#249 Update Pull Request template to include checklist
  .github/PULL_REQUEST_TEMPLATE.md
Labels: Improvement, Repo Misc
