Repository FuelLabs/sway-libs, pull requests merged in 2025-01, with the labels that each got.

#317 Update rust versions to v1.83.0
  .github/workflows/ci.yml
  .github/workflows/gh-pages.yml
  CHANGELOG.md
Labels: Improvement

#318 Improve signed integer docs
  CHANGELOG.md
  docs/book/spell-check-custom-words.txt
  docs/book/src/signed_integers/index.md
  examples/signed_integers/src/main.sw
Labels: Documentation, Lib: Math, Libs: Data Structures

#321 Typo fix in specification.md
  docs/contributing-book/src/code_docs/specification.md
Labels: cla:signed

#322 Expand asset library docs
  CHANGELOG.md
  docs/book/src/asset/metadata.md
  examples/asset/metadata_docs/src/main.sw
  examples/asset/setting_src7_attributes/src/main.sw
Labels: Documentation, Lib: Asset

#323 Update to forc `v0.66.6`
  .github/workflows/ci.yml
  .github/workflows/gh-pages.yml
  README.md
  docs/book/src/getting_started/index.md
  docs/contributing-book/src/code/Forc.lock
  docs/contributing-book/src/code/connect_four/src/main.sw
  examples/Forc.lock
  libs/Forc.lock
  libs/src/admin.sw
  libs/src/bytecode/utils.sw
  libs/src/signed_integers/i128.sw
  libs/src/signed_integers/i16.sw
  libs/src/signed_integers/i256.sw
  libs/src/signed_integers/i32.sw
  libs/src/signed_integers/i64.sw
  libs/src/signed_integers/i8.sw
  tests/Forc.lock
  tests/src/bytecode/test_artifacts/complex_contract/src/main.sw
  tests/src/bytecode/tests/utils/mod.rs
  tests/src/reentrancy/reentrancy_attacker_contract/src/main.sw
Labels: Repo Misc
